version: '3.8'

services:
  jaeger-aio:
    image: jaegertracing/all-in-one:1.20.0
    ports:
      - "16686:16686" 
      - "6831:6831/udp"
    environment:
      - ES_SERVER_URLS=http://elasticsearch:9200
      - SPAN_STORAGE_TYPE=elasticsearch
      - LOG_LEVEL=debug
    restart: on-failure
    depends_on:
        - elasticsearch
        
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.9.3
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200/tcp"
      - "9300:9300"

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:7.9.3
    container_name: kibana
    environment:
      - "ELASTICSEARCH_URL=http://elasticsearch:9200"
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch